name: ✨ Feature Request
description: 提出一个新功能或改进建议
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: 功能概述
      description: 解决什么问题？面向哪类用户？
    validations:
      required: true
  - type: textarea
    id: spec
    attributes:
      label: 规格初稿（可直接用于生成）
      description: 用自然语言写清输入、交互、验收标准
      placeholder: |
        功能：
        技术边界：
        验收标准：
    validations:
      required: true
  - type: checkboxes
    id: scope
    attributes:
      label: 影响范围
      options:
        - label: 新页面
        - label: 新组件
        - label: 变更现有组件
        - label: 仅文档/模板
  - type: textarea
    id: refs
    attributes:
      label: 参考/灵感（链接）
